server:
  port: 9000

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/banking-realm

      client:
        registration:
          transaction-client:
            provider: keycloak
            client-id: transaction-client
            client-secret: 41G2KIDPqHeu1Ae9vETsZfuyelSH5Ii8
            authorization-grant-type: client_credentials

        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/banking-realm/protocol/openid-connect/token

  cloud:
    gateway:
      routes:

        - id: account-service
          uri: http://localhost:8081
          predicates:
            - Path=/accounts/**

        - id: transaction-service
          uri: http://localhost:8082
          predicates:
            - Path=/transactions/**

management:
  endpoints:
    web:
      exposure:
        include: health,info