server:
  port: 8081

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:h2:mem:accountdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/banking-realm

management:
  endpoints:
    web:
      exposure:
        include: health,info